### ISSUE TITLE
using index.standalone.html

### ISSUE THREAD

**Issue by yafred** [ornicar/chessground-examples#16]
Hi,

I am missing this file
```
<script src="../node_modules/chessground/dist/chessground.js"></script>
```

Should the file be created when you follow the readme ?
```
yarn install
yarn exec gulp dev
```

Thanks

**Comment by niklasf** [comment]
New link: https://github.com/lichess-org/chessground/blob/master/demo.html (build instructions in https://github.com/lichess-org/chessground/blob/master/README.md apply).
