### ISSUE TITLE
Cursed 8x9 board in 3d view

### ISSUE THREAD

**Issue by jacksonthall22** [ornicar/chessground-examples#34]
![image](https://github.com/lichess-org/chessground-examples/assets/25040219/4fc3962e-423f-4824-af86-31e84a566ecc)

**Comment by niklasf** [comment]
Thanks! Fixed.

**Comment by jacksonthall22** [comment]
On page load it looks normal (although larger than the 2d boards in the other routes), but changing the zoom to some other value then back to 100 seems to break it again:

![image](https://github.com/lichess-org/chessground-examples/assets/25040219/a7576389-2980-467e-9395-84d849300d6c)
